git:
  quiet: true
language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.8
    dist: xenial
    sudo: true
before_install:
  - sudo apt-get install -y iverilog
install:
  - pip install pipenv
  - pipenv install
  - pytest test/